services:
  builder:
    build:
      context: .
      dockerfile: docker/Dockerfile.x86
    environment:
      - GIT_HASH=${GIT_HASH}
    tty: true
    stdin_open: true
    volumes:
      - "~/tmp-x86/build:/build:Z"
      - "./:/webview:ro"
      - "./scripts/build_x86_webview.sh:/scripts/build_x86_webview.sh"
