name: Build Webview

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-webview.yaml'
      - 'webview/**'
      - '!webview/README.md'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build-webview.yaml'
      - 'webview/**'
      - '!webview/README.md'

jobs:
  compile-webview:
    strategy:
      matrix:
        board: ['pi1', 'pi2', 'pi3', 'pi4']
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        run: |
          cd webview/
          docker buildx build \
            --load \
            --build-arg GIT_HASH=$(git rev-parse --short HEAD) \
            -t qt-builder .

      - name: Build WebView for ${{ matrix.board }}
        shell: 'script -q -e -c "bash {0}"'
        run: |
          cd webview/
          docker run -itd \
            --name qt-builder-instance \
            -v ~/tmp/qt-src:/src:Z \
            -v ~/tmp/qt-build:/build:Z \
            -v $(pwd):/webview:ro \
            -e TARGET="${{ matrix.board }}" \
            qt-builder
          docker exec -it qt-builder-instance /webview/build_webview_with_qt5.sh
          docker rm -f qt-builder-instance

      - name: 'DEBUG: List files in ~/tmp/qt-build'
        run: |
          ls -lah ~/tmp/qt-build

      - uses: actions/upload-artifact@v4
        with:
          name: webview-${{ matrix.board }}
          path: ~/tmp/qt-build/
